name: Install Dependencies

on: workflow_call

jobs:
  Install-Dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --quiet --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install