name: Set up Python

on: workflow_call

jobs:
  Set-up-Python:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
